dist: xenial
language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
    - nightly
jobs:
    fast_finish: true
    allow_failures:
        - python: nightly
install:
    - pip install --requirement requirements-dev.txt
    - pip install --editable .
script:
    - pytest
